const listadoPueblos = [
'Abadiño', 'Abaurrea Alta', 'Abaurregaina', 'Abezia', 'Aduna', 'Agurain', 'Aia', 'Aizarnazabal', 'Ametzagaina',
  'Amorebieta-Etxano', 'Amurrio', 'Andoain', 'Areatza', 'Arrasate (Mondragón)', 'Arrigorriaga', 'Aramaio', 'Arantzazu',
  'Artea', 'Arratia-Nervión', 'Arbizu', 'Arkaia', 'Ariz', 'Arrieta', 'Asteasu', 'Atxondo', 'Azkoitia', 'Azpeitia',
  'Balmaseda', 'Barakaldo', 'Basozelai', 'Beasain', 'Bermeo', 'Berriatua', 'Berriz', 'Bidegoian', 'Bilbao', 'Elgoibar',
  'Elorrio', 'Erandio', 'Ermua', 'Etxebarri', 'Etxarri-Aranatz', 'Galdakao', 'Galdames', 'Getaria', 'Getxo', 'Gernika-Lumo',
  'Goierri', 'Gorliz', 'Hernani', 'Hondarribia', 'Igorre', 'Irun', 'Itziar', 'Karrantza', 'Kortezubi', 'Lasarte-Oria',
  'Lemoa', 'Lezo', 'Lekeitio', 'Legazpi', 'Markina-Xemein', 'Mendaro', 'Mungia', 'Mutriku', 'Ondarroa', 'Oñati', 'Orio',
  'Ortuella', 'Pasaia', 'Portugalete', 'Rentería', 'San Sebastián (Donostia)', 'Santo Domingo', 'Santurzi', 'Sopelana',
  'Tolosa', 'Trapagaran', 'Urnieta', 'Usurbil', 'Vitoria-Gasteiz', 'Zarautz', 'Zalla', 'Zegama', 'Zumaia', 'Aia',
  'Alonsotegi', 'Ametzagaina', 'Amorebieta-Etxano', 'Aretxabaleta', 'Arrasate', 'Arrigorriaga', 'Artea', 'Azpeitia',
  'Beasain', 'Bermeo', 'Berriatua', 'Bilbao', 'Elgoibar', 'Elorrio', 'Etxebarri', 'Galdakao', 'Getaria', 'Getxo',
  'Gernika-Lumo', 'Goierri', 'Gorliz', 'Hernani', 'Hondarribia', 'Igorre', 'Irun', 'Itziar', 'Karrantza', 'Kortezubi',
  'Lasarte-Oria', 'Lemoa', 'Lezo', 'Lekeitio', 'Legazpi', 'Markina-Xemein', 'Mendaro', 'Mungia', 'Mutriku', 'Ondarroa',
  'Oñati', 'Orio', 'Ortuella', 'Pasaia', 'Portugalete', 'Rentería', 'San Sebastián', 'Santo Domingo', 'Santurzi',
  'Sopelana', 'Tolosa', 'Trapagaran', 'Urnieta', 'Usurbil', 'Vitoria-Gasteiz', 'Zarautz', 'Zalla', 'Zegama', 'Zumaia',
  'Abaurrea Alta', 'Abaurregaina', 'Aduna', 'Agurain', 'Aia', 'Aizarnazabal', 'Ametzagaina', 'Amorebieta-Etxano',
  'Amurrio', 'Andoain', 'Areatza', 'Arrasate (Mondragón)', 'Arrigorriaga', 'Aramaio', 'Arantzazu', 'Artea', 'Arbizu',
  'Arkaia', 'Ariz', 'Arrieta', 'Asteasu', 'Atxondo', 'Azkoitia', 'Azpeitia', 'Balmaseda', 'Barakaldo', 'Basozelai',
  'Beasain', 'Bermeo', 'Berriatua', 'Berriz', 'Bidegoian', 'Bilbao', 'Elgoibar', 'Elorrio', 'Etxebarri', 'Etxarri-Aranatz',
  'Galdakao', 'Galdames', 'Getaria', 'Getxo', 'Gernika-Lumo', 'Goierri', 'Gorliz', 'Hernani', 'Hondarribia', 'Igorre',
  'Irun', 'Itziar', 'Karrantza', 'Kortezubi', 'Lasarte-Oria', 'Lemoa', 'Lezo', 'Lekeitio', 'Legazpi', 'Markina-Xemein',
  'Mendaro', 'Mungia', 'Mutriku', 'Ondarroa', 'Oñati', 'Orio', 'Ortuella', 'Pasaia', 'Portugalete', 'Rentería',
  'San Sebastián', 'Santo Domingo', 'Santurzi', 'Sopelana', 'Tolosa', 'Trapagaran', 'Urnieta', 'Usurbil', 'Vitoria-Gasteiz',
  'Zarautz', 'Zalla', 'Zegama', 'Zumaia', 'Aia', 'Alonsotegi', 'Ametzagaina', 'Amorebieta-Etxano', 'Aretxabaleta',
  'Arrasate', 'Arrigorriaga', 'Artea', 'Azpeitia', 'Beasain', 'Bermeo', 'Berriatua', 'Bilbao', 'Elgoibar', 'Elorrio',
  'Etxebarri', 'Galdakao', 'Getaria', 'Getxo', 'Gernika-Lumo', 'Goierri', 'Gorliz', 'Hernani', 'Hondarribia', 'Igorre',
  'Irun', 'Itziar', 'Karrantza', 'Kortezubi', 'Lasarte-Oria', 'Lemoa', 'Lezo', 'Lekeitio', 'Legazpi', 'Markina-Xemein',
  'Mendaro', 'Mungia', 'Mutriku', 'Ondarroa', 'Oñati', 'Orio', 'Ortuella', 'Pasaia', 'Portugalete', 'Rentería',
  'San Sebastián', 'Santo Domingo', 'Santurzi', 'Sopelana', 'Tolosa', 'Trapagaran', 'Urnieta', 'Usurbil', 'Vitoria-Gasteiz',
  'Zarautz', 'Zalla', 'Zegama', 'Zumaia', 'Abaurrea Alta', 'Abaurregaina', 'Aduna', 'Agurain', 'Aia', 'Aizarnazabal',
  'Ametzagaina', 'Amorebieta-Etxano', 'Amurrio', 'Andoain', 'Areatza', 'Arrasate (Mondragón)', 'Arrigorriaga', 'Aramaio',
  'Arantzazu', 'Artea', 'Arbizu', 'Arkaia', 'Ariz', 'Arrieta', 'Asteasu', 'Atxondo', 'Azkoitia', 'Azpeitia', 'Balmaseda',
  'Barakaldo', 'Basozelai', 'Beasain', 'Bermeo', 'Berriatua', 'Berriz', 'Bidegoian', 'Bilbao', 'Elgoibar', 'Elorrio',
  'Etxebarri', 'Etxarri-Aranatz', 'Galdakao', 'Galdames', 'Getaria', 'Getxo', 'Gernika-Lumo', 'Goierri', 'Gorliz',
  'Hernani', 'Hondarribia', 'Igorre', 'Irun', 'Itziar', 'Karrantza', 'Kortezubi', 'Lasarte-Oria', 'Lemoa', 'Lezo',
  'Lekeitio', 'Legazpi', 'Markina-Xemein', 'Mendaro', 'Mungia', 'Mutriku', 'Ondarroa', 'Oñati', 'Orio', 'Ortuella',
  'Pasaia', 'Portugalete', 'Rentería', 'San Sebastián', 'Santo Domingo', 'Santurzi', 'Sopelana', 'Tolosa', 'Trapagaran',
  'Urnieta', 'Usurbil', 'Vitoria-Gasteiz', 'Zarautz', 'Zalla', 'Zegama'
];

export default { listadoPueblos} ;